[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_FIREBASE_API_KEY = "votre_api_key"
  NEXT_PUBLIC_FIREBASE_APP_ID = "votre_app_id"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "votre_auth_domain"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "votre_measurement_id"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "votre_messaging_sender_id"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "votre_project_id"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "votre_storage_bucket"
  NEXT_PUBLIC_TINYMCE_API_KEY = "votre_tinymce_api_key"
  NEXT_DISABLE_ESLINT = "true"
  NEXT_DISABLE_TYPE_CHECKING = "true"